/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "tftp.h"

bool_t
xdr_op_t (XDR *xdrs, op_t *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_reqt_t (XDR *xdrs, reqt_t *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_blockn_t (XDR *xdrs, blockn_t *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_errcode_t (XDR *xdrs, errcode_t *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_req_t (XDR *xdrs, req_t *objp)
{
	register int32_t *buf;

	 if (!xdr_reqt_t (xdrs, &objp->reqtype))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->filename, MAX_FILENAME_LEN))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->mode, MAX_MODE_LEN))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_dat_t (XDR *xdrs, dat_t *objp)
{
	register int32_t *buf;

	 if (!xdr_blockn_t (xdrs, &objp->blocknum))
		 return FALSE;
	 if (!xdr_bytes (xdrs, (char **)&objp->payload.payload_val, (u_int *) &objp->payload.payload_len, MAX_BLOCK_LEN))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ack_t (XDR *xdrs, ack_t *objp)
{
	register int32_t *buf;

	 if (!xdr_blockn_t (xdrs, &objp->blocknum))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_err_t (XDR *xdrs, err_t *objp)
{
	register int32_t *buf;

	 if (!xdr_errcode_t (xdrs, &objp->errcode))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->errstr, MAX_ERRSTR_LEN))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_msg_t (XDR *xdrs, msg_t *objp)
{
	register int32_t *buf;

	 if (!xdr_op_t (xdrs, &objp->op))
		 return FALSE;
	switch (objp->op) {
	case REQ:
		 if (!xdr_req_t (xdrs, &objp->msg_t_u.req))
			 return FALSE;
		break;
	case DAT:
		 if (!xdr_dat_t (xdrs, &objp->msg_t_u.dat))
			 return FALSE;
		break;
	case ACK:
		 if (!xdr_ack_t (xdrs, &objp->msg_t_u.ack))
			 return FALSE;
		break;
	case ERR:
		 if (!xdr_err_t (xdrs, &objp->msg_t_u.err))
			 return FALSE;
		break;
	default:
		return FALSE;
	}
	return TRUE;
}
